version: '3.8'
services:
  web:
    build: .
    ports:
<<<<<<< HEAD
      - "9090:80"
    volumes:
      - ./www:/var/www/html
=======
      - "8080:80"
    volumes:
      - .:/var/www/html
>>>>>>> 9194cda (first commit)
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
